# Generated by Django 5.2.11 on 2026-02-11 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_tag_alter_article_contenu_article_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Guinée', max_length=100)),
                ('site_web', models.URLField(blank=True)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.CharField(blank=True, max_length=100)),
                ('articles_publies', models.PositiveIntegerField(default=0)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_auteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Auteur',
                'verbose_name_plural': 'Profils Auteurs',
            },
        ),
    ]
